# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CancalLoad' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CancalLoad
  pod 'AFNetworking', '~> 3.2.1'
  pod 'MBProgressHUD', '~> 1.1.0'

end
